[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "kn-en-translator"
version = "0.1.0"
description = "Kannada to English translator using Transformers"
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.9"
readme = "README.md"
